[profile.default]
solc_version = '0.8.20'
src = 'interfaces'
test = 'tests/integrations'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 512
# @see {@link https://github.com/foundry-rs/foundry/issues/4060}
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
build_info = true

via_ir = true
fuzz_runs = 500
deny_warnings = false

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[fmt]
line_length = 160
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
ignore = ["libs/*","*.t.sol"]
